microcreditos/src/Entity/Grupo.php
<?php

namespace App\Entity;
use App\Entity\Base\BaseClass;
use Doctrine\ORM\Mapping as ORM;
/**
 * \App\Entity\Grupo
 *
 * @ORM\Table(name="grupo")
 * @ORM\Entity(repositoryClass="App\Repository\GrupoRepository")
 * @ORM\HasLifecycleCallbacks()
 */

class Grupo extends BaseClass
{
   
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;
    
    /**
     * @var string $codigo
     *
     * @ORM\Column(name="codigo", type="string", length=6)
     */
    protected $codigo;
    
    /**
     * @var string $nombre
     *
     * @ORM\Column(name="nombre", type="string", length=100)
     */
    protected $nombre;
    
    /**
     * @var integer $activo
     *
     * @ORM\Column(name="activo", type="boolean")
     */
    protected $activo;
    
    /**
     * @var integer $fechaAlta
     *
     * @ORM\Column(name="fecha_alta", type="datetime")
     */
    protected $fechaAlta;

    /**
     * @ORM\OneToMany(targetEntity="GruposEmprendedores", mappedBy="grupo",cascade={"persist","remove"})
     */
    protected $emprendedores;
    
    /**
     *@ORM\OneToMany(targetEntity="Credito", mappedBy="grupo")
     *@ORM\OrderBy({"nroRenovacion" = "DESC"}) 
     */
    protected $creditos;
    
    /**
     *@ORM\ManyToOne(targetEntity="Programa", inversedBy="grupos")
     *@ORM\JoinColumn(name="programa_id", referencedColumnName="id") 
     */
    protected $programa;    
    
    /**
     *@ORM\ManyToOne(targetEntity="User", inversedBy="grupos")
     *@ORM\JoinColumn(name="usuario_id", referencedColumnName="id") 
     */
    protected $usuario;
    
    /**
     *@ORM\ManyToOne(targetEntity="Emprendedor", inversedBy="recomendado")
     *@ORM\JoinColumn(name="recomendador_id", referencedColumnName="id") 
     */
    protected $recomendador;


    public function __toString() {
        return $this->nombre;
    }
    
    public function getTitle(){
        return '" '.$this->nombre.' "';
    }
    
    public function __construct()
    {
        $this->emprendedores = new \Doctrine\Common\Collections\ArrayCollection();
        $this->activo = true;
    }
 
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set codigo
     *
     * @param string $codigo
     */
    public function setCodigo($codigo)
    {
        $this->codigo = $codigo;
    }

    /**
     * Get codigo
     *
     * @return string 
     */
    public function getCodigo()
    {
        return $this->codigo;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set activo
     *
     * @param boolean $activo
     */
    public function setActivo($activo)
    {
        $this->activo = $activo;
    }

    /**
     * Get activo
     *
     * @return boolean 
     */
    public function getActivo()
    {
        return $this->activo;
    }

    /**
     * Add emprendedores
     *
     * @param \App\Entity\GruposEmprendedor $emprendedores
     */
    public function addGruposEmprendedores(\App\Entity\GruposEmprendedores $emprendedores)
    {
        $this->emprendedores[] = $emprendedores;
    }

    /**
     * Get emprendedores
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getGruposEmprendedores()
    {
        return $this->emprendedores;
    }

    public function getEmprendedores(){
        $array = array();
        foreach($this->getGruposEmprendedores() as $gruposEmprendedor){
            $array[] = $gruposEmprendedor->getEmprendedor();
        }
        return $array;
    }

    /**
     * Set programa
     *
     * @param \App\Entity\Programa $programa
     */
    public function setPrograma(\App\Entity\Programa $programa)
    {
        $this->programa = $programa;
    }

    /**
     * Get programa
     *
     * @return \App\Entity\Programa
     */
    public function getPrograma()
    {
        return $this->programa;
    }
    
    /**
     * @ORM\PrePersist
     */
    public function setAlta()
    {
        $this->fechaAlta = new \DateTime();
        $this->activo = 1;
    }    

    /**
     * Set fechaAlta
     *
     * @param datetime $fechaAlta
     */
    public function setFechaAlta($fechaAlta)
    {
        $this->fechaAlta = $fechaAlta;
    }

    /**
     * Get fechaAlta
     *
     * @return datetime 
     */
    public function getFechaAlta()
    {
        return $this->fechaAlta;
    }

    /**
     * Set usuario
     *
     * @param \App\Entity\User $usuario
     */
    public function setUsuario(\App\Entity\User $usuario)
    {
        $this->usuario = $usuario;
    }

    /**
     * Get usuario
     *
     * @return \App\Entity\User
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    /**
     * Add creditos
     *
     * @param \App\Entity\Credito $creditos
     */
    public function addCredito(\App\Entity\Credito $creditos)
    {
        $this->creditos[] = $creditos;
    }

    /**
     * Get creditos
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getCreditos()
    {
        return $this->creditos;
    }

    /**
     * Set recomendador
     *
     * @param \App\Entity\Emprendedor $recomendador
     */
    public function setRecomendador($recomendador)
    {
        $this->recomendador = ($recomendador)?$recomendador:null;;
    }

    /**
     * Get recomendador
     *
     * @return \App\Entity\Emprendedor
     */
    public function getRecomendador()
    {
        return $this->recomendador;
    }

    public function getStatus(){
        return 'ok';
    }
}

microcreditos/src/Form/GrupoType.php
<?php

namespace App\Form;

use App\Entity\Emprendedor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class GrupoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('codigo',TextType::class,array('label'=>'Código:'))
            ->add('nombre',TextType::class,array('label'=>'Nombre:'))
            ->add('activo',CheckboxType::class,array('label'=>'Activo:','required'=>false))
            ->add('programa',null,array('label'=>'Programa de Fondos:'))
//            ->add('recomendador','emprendedor_selector',array('label'=>'RECOMENDADO POR:','required'=>false))
            ->add('recomendador', EntityType::class,
                array(  'label' => 'RECOMENDADO POR:',
                    'required' => false,
                    'class' => Emprendedor::class,
                )
            )
        ;
    }

    public function getName()
    {
        return 'microcreditos_microcreditosbundle_grupotype';
    }
}

microcreditos/src/Controller/GrupoController.php
<?php
namespace App\Controller;

use App\Entity\GruposEmprendedores;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use App\Controller\CreditoController;
use App\Entity\Grupo;
use App\Form\GrupoType;

/**
 * Grupo controller.
 *
 */
class GrupoController extends Controller
{
    /**
     * Lists all Grupo entities.
     *
     */
    public function indexAction()
    {
        $request = $this->container->get('request_stack')->getCurrentRequest();
        $session = $request->getSession();
        $sessionFiltro = $session->get('filtro_grupo');
        switch ($request->get('_opFiltro')) {
            case 'limpiar':
                $filtro = array('programa'=>'','grupo'=>'','grupoId'=>'','desde'=>'','hasta'=>'','itemsperpage'=>20);
                break;
            case 'buscar':
                $filtro = array(
                    'programa'  =>$request->get('_programa'),
                    'grupo'     =>$request->get('_grupo'),
                    'grupoId'   =>$request->get('_grupoId'),
                    'desde'     =>$request->get('_desde'),
                    'hasta'     =>$request->get('_hasta'),
                    'itemsperpage' => 20
                    );
                break;
            default:
                //desde paginacion, se usa session
                $filtro = array(
                    'programa'  =>$sessionFiltro['programa'],
                    'grupo'     =>$sessionFiltro['grupo'],
                    'grupoId'   =>$sessionFiltro['grupoId'],
                    'desde'     =>$sessionFiltro['desde'],
                    'hasta'     =>$sessionFiltro['hasta'],
                    'itemsperpage' => 20
                );
                break;
        }
                   
        $session->set('filtro_grupo',$filtro);
        $em = $this->getDoctrine()->getManager();

        $paginator = $this->get('knp_paginator');
        $query = null;
        $varItems = ($filtro['itemsperpage']==0) ? 1000 : $filtro['itemsperpage'];
        $query =  $em->getRepository('App:Grupo')
            ->findByMyFiltroDQL($session->get('filtro_grupo'));

        $entities = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        foreach ($entities as $grupo) {
            CreditoController::setUltimaCuota($grupo->getCreditos(), $em);
        }

        $programas = $em->getRepository('App:Programa')->findByActivosDQL();
        $vars = array(  
            'entityName'   => 'grupo',
            'filtro'       => $session->get('filtro_grupo'),
            'programas'    => $programas, 
            'entities'     => $entities,
            'paginator'    => $paginator);
       
        return $this->render('Grupo/grupoIndex.html.twig', $vars );
    }

    /**
     * Finds and displays a Grupo entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('App:Grupo')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('No existe el Grupo que está buscando.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm(GrupoType::class, $entity);

        return $this->render('Grupo/show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
            'form'   => $editForm->createView()

        ));
    }

    /**
     * Displays a form to create a new Grupo entity.
     *
     */
    public function newAction()
    {
        $entity = new Grupo();
        $em = $this->getDoctrine()->getManager();
        $ultimo = $em->getRepository('App:Parametro')->getUltimoNroDQL('Grupo');
        $nro = $ultimo->getNumerico()+1;
        $codigo = $ultimo->getDescripcion().str_pad($nro,3,"0",STR_PAD_LEFT);
        $entity->setCodigo($codigo);
        $form   = $this->createForm(GrupoType::class, $entity);

        return $this->render('Grupo/grupoEdit.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
    }

    /**
     * Creates a new Grupo entity.
     *
     */
    public function createAction()
    {
        $entity  = new Grupo();
        $request = $this->container->get('request_stack')->getCurrentRequest();
        $form    = $this->createForm(GrupoType::class, $entity);

        if ($request->isMethod('POST')) {
            $form->submit($request->get($form->getName()));
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $ultimo = $em->getRepository('App:Parametro')->getUltimoNroDQL('Grupo');
                $nro = $ultimo->getNumerico()+1;
                $codigo = $ultimo->getDescripcion().str_pad($nro,3,"0",STR_PAD_LEFT);
                $ultimo->setNumerico($nro);
                $entity->setCodigo($codigo);
                $em->persist($entity);
                $em->persist($ultimo);
                $em->flush();
                $session = $request->getSession();
                $session->getFlashBag()->set('success','El Grupo se ha creado con éxito.');
                return $this->redirect($this->generateUrl('grupo_edit', array('id' => $entity->getId())));

            }
        }

        return $this->render('Grupo/grupoEdit.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
    }

    /**
     * Displays a form to edit an existing Grupo entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('App:Grupo')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('No existe el Grupo que está buscando.');
        }

        $puedeModificarse = true;
        foreach($entity->getCreditos() as $credito){
            if($credito->getAprobado()){
                if(DefaultController::controlaCredititoActivo($credito->getStatus()) ==  false){
                    $puedeModificarse= false;
                }
            }
        }

        if($puedeModificarse == false){
            $request = $this->container->get('request_stack')->getCurrentRequest();
            $session = $request->getSession();
            $session->getFlashBag()->set('error','No se pudo editar el Grupo por que tiene Creditos entregados');
            return $this->redirect($this->generateUrl('grupo_show', array('id' => $id)));
        }

       // $page = pathinfo($this->getRequest()->headers->get('referer'),PATHINFO_BASENAME);
        $editForm = $this->createForm(GrupoType::class, $entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('Grupo/grupoEdit.html.twig', array(
            'entity'      => $entity,
            //'page'   => (strpos($page, 'page'))?$page:'', 
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Edits an existing Grupo entity.
     *
     */
    public function updateAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('App:Grupo')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('No existe el Grupo que está buscando.');
        }

        $editForm   = $this->createForm(GrupoType::class, $entity);
        $deleteForm = $this->createDeleteForm($id);

        $request = $this->container->get('request_stack')->getCurrentRequest();

        if ($request->isMethod('POST')) {
            $editForm->submit($request->get($editForm->getName()));
            if ($editForm->isValid()) {
                $em->persist($entity);
                $em->flush();
                $session = $request->getSession();
                $session->getFlashBag()->set('success','Los cambios se han guardado con éxito');
                return $this->redirect($this->generateUrl('grupo_edit', array('id' => $id)));
            }
        }

        return $this->render('Grupo/grupoEdit.html.twig', array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a Grupo entity.
     *
     */
    public function deleteAction($id)
    {
        $form = $this->createDeleteForm($id);
        $request = $this->container->get('request_stack')->getCurrentRequest();

        if ($request->isMethod('POST')) {
            $form->submit($request->get($form->getName()));
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $entity = $em->getRepository('App:Grupo')->find($id);

                if (!$entity) {
                    throw $this->createNotFoundException('No existe el Grupo que está buscando.');
                }

                if(count($entity->getCreditos()) > 0){
                    $session = $request->getSession();
                    $session->getFlashBag()->set('error','No se pudo borrar el Grupo por que tiene Creditos entregados');
                    return $this->redirect($this->generateUrl('grupo_edit', array('id' => $id)));
                }

                $em->remove($entity);
                $em->flush();
            }
        }

        return $this->redirect($this->generateUrl('grupo'));
    }

    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', HiddenType::class)
            ->getForm()
        ;
    }
/* Suggest de grupos */
    public function getGrupoSuggestAction(){
        $request = $this->container->get('request_stack')->getCurrentRequest();
        $term = $request->get('term');

microcreditos/templates/Grupo/_partial_emprendedor.html.twig
<div id="datosEmprendedor"></div>
<table id="emprendedores">
            <thead>
                <tr>
                    <th class="align-center">Código</th>
                    <th>Apellido</th>
                    <th>Nombres</th>
                    <th>DNI</th>
                    <th>Dirección</th>
                    <th class="align-center">Fecha Alta</th>
                    <th style="width:10%" class="align-center actions"></th>
                </tr>
            </thead>
            <tbody>
{% for emprendedor in entity.emprendedores %}
    <tr>
        <td class="align-center">{{ emprendedor.codigo }}</td>
        <td>{{ emprendedor.apellido }}</td>
        <td>{{ emprendedor.nombres }}</td>
        <td>{{ emprendedor.dni }}</td>
        <td>{{ emprendedor.direccion }}</td>
        <td class="align-center">{{ emprendedor.fechaAlta|date('d-m-Y') }}</td>
        <td>
            <span onclick="editEmprendedor({{emprendedor.id}})" class="action mini-edit programa_ingreso_edit" title="Editar" >
                Editar
            </span>
            <span onclick="deleteEmprendedorGrupo({{emprendedor.id}})" class="action delete programa_ingreso_delete" title="Quitar del Grupo">
                Quitar
            </span>
        </td>
    </tr>
{% endfor %}                
                
              
             </tbody>
        </table>
<script type="text/javascript">
    $(document).ready(function(){
         $('tbody tr:even').addClass("alt-row");
    });
</script>             

microcreditos/templates/Grupo/grupoEdit.html.twig
{% extends "Default/baseEditEntity.html.twig" %}
{% block pageTitle %} <h2>Grupos de Emprendedores </h2>{% endblock %}
{% block pathback %}   {{ path('grupo') }}  {% endblock %}

{% block tabs %} 
<ul class="content-box-tabs">
    <li><a href="#tabGroup1" class="default-tab"><strong>GRUPO</strong></a></li> 
    {% if entity.id  %}<li><a href="#tabGroup2" >Emprendedores</a></li> {%endif%}
    {% if entity.id  %}<li><a href="#tabGroup3" >Creditos Entregados</a></li> {%endif%}
</ul>
{% endblock%}

{% block groupFormContent %}
<div class="tab-content default-tab" id="tabGroup1">   
    {% if entity.id  %}
        <div class="align-right">
            <form action=" {{path('grupo_delete', { 'id': entity.id })}}" method="post">
                {{ form_widget(delete_form) }}
                <button type="submit" title="Eliminar" class="action deleteMax">Eliminar</button>
            </form>
        </div>
        <form action="{{path('grupo_update', { 'id': entity.id })}}" method="post"  >
  {% else %}
        <form action="{{ path('grupo_create') }} " method="post"  >
  {%endif%}
            <fieldset>
                <p>
                    {{ form_label(form.codigo) }}
                    {{ form_widget(form.codigo, { 'attr': {'class' : 'text-input smaller-input', 'readonly':'readonly' } }) }}
                    {{ form_errors(form.codigo) }}
                </p>
                <p>
                    {{ form_label(form.nombre) }}
                    {{ form_widget(form.nombre, { 'attr': { 'class' : 'text-input medium-input' } }) }}
                    {{ form_errors(form.nombre) }}
                </p>
                <p>
                    {{ form_label(form.programa) }}
                    {{ form_widget(form.programa, { 'attr': { 'class' : 'text-input smaller-input', 'url' : path('es_programa_individual') } }) }}
                    {{ form_errors(form.programa) }}
                </p>
                <p>
                    {{ form_label(form.recomendador) }}
                    {{ form_widget(form.recomendador) }}
                 </p>
                <p>
                    {{ form_label(form.activo) }}
                    {{ form_widget(form.activo) }}
                    {{ form_errors(form.activo) }}
                </p>

            </fieldset>
            <p class="submit-block">
                <button type="submit" class="button">Guardar</button>
            </p>
            {{ form_rest(form) }}
        </form>
         <div class="clear"></div>
</div>

<div class="tab-content" id="tabGroup2">
    <div class="content-box">
        <div class="content-box-header">
            <h3>Emprendedores del Grupo</h3>
            <span class="align-right total">Total: {{ entity.emprendedores | length }}</span>
        </div> <!-- End .content-box-header -->
        <div class="content-box-content">
            {% include "Grupo/_partial_emprendedor.html.twig" %}
            <div class="clear"></div>
        </div>

        <div id="divAddEmprendedor" >
            <form style="text-align: center ">
                <div style="margin: 10px">
                    <label><strong>Agregar Emprendedor:</strong></label>
                    <input name="_emprendedor" url="{{ path('emprendedor_suggest') }}" class="text-input small-input" id="emprendedorAutocomple" />
                    <input type="hidden" name="_emprendedorId" value="" id="emprendedorId" />
                    <span class="button" value="Agregar" id="addEmprendedor" style="margin: 5px">Agregar</span>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="tab-content" id="tabGroup3">
    <div class="content-box">
        <div class="content-box-header">
            <h3>Creditos entregados</h3>
            <span class="align-right total">Total: {{ entity.creditos | length }}</span>
        </div> <!-- End .content-box-header -->
        <div class="content-box-content">
            <table>
                <thead>
                <tr>
                    <th>Creditos</th>
                    <th class="align-center">Status</th>
                    <th class="align-center">Fecha</th>
                    <th class="align-center">Cantidad Cuotas</th>
                    <th class="align-center">Monto</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for creditoEntry in entity.creditos %}
                    <tr>
                        <td>{{ creditoEntry }}</td>
                        <td class="align-center">
                            {% if creditoEntry.status == 'Moroso' %}
                                <b style="color: #FF4500!important;">{{ creditoEntry.status }}</b>
                            {% else %}
                                {{ creditoEntry.status }}
                            {% endif %}
                        </td>
                        <td class="align-center">{{creditoEntry.fechaEntrega | date('d-m-Y')}}</td>
                        <td class="align-center">
                            {%  if creditoEntry.aprobado == 1 %}
                            {{ creditoEntry.ultimaCuotaPaga }}/{{creditoEntry.cantCuotas}}</td>
                        {% else %}
                            Solicitud/{{creditoEntry.cantCuotas}}</td>
                        {% endif %}
                        <td style="text-align:right">{{creditoEntry.montoCredito| number_format(0,',','.')}}</td>
                        <td>
                            <a href="{{ path('credito_show', { 'id': creditoEntry.id }) }}" title="Ver"><img src="{{ asset('images/icons/credit.png') }}" alt="Ver" /></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="clear"></div>
        </div>
    </div>
</div>

<script type="text/javascript">    
    $(document).bind('beforeReveal.facebox', function() {
            $('#facebox .content').width('600px');
    });

    $(document).bind('afterClose.facebox', function() {
          $("#emprendedorId").val('');
        //  $('#emprendedorAutocomple').val('');
           $.ajax({
                    url: '{{path("grupo_remove_emprendedor")}}',
                    data: 'empId='+'&grupoId='+'{{entity.id}}',
                    dataType: 'json',
                    success: function(data){
                        $('#emprendedores').html(data.partial);
                   }
                });
    });

    $(document).ready(function(){
         $('tbody tr:even').addClass("alt-row");

        $('#addEmprendedor').click(function(){
            $('#loading').fadeIn();
            $.ajax({
                url: '{{path("grupo_add_emprendedor")}}',
                data: 'empId='+$('#emprendedorId').val()+'&grupoId='+'{{entity.id}}',
                //async:false,
                dataType: 'json',
                success: function(data){
                    if(data.msg)
                        alert(data.msg);
                    else{
                        $('#emprendedores').html(data.partial);
                    }
                    $("#emprendedorId").val('');
                    $('#emprendedorAutocomple').val('');
                    $('#loading').fadeOut();
               }
            });
        });

        // addOptionEmptyToSelect('emprendedor_grupo');

        $('#grupo_programa').select2({
            allowClear: true,
            placeholder: 'Seleccione una opción'
        });

        // addOptionEmptyToSelect('emprendedor_grupo');
        $('#grupo_recomendador').select2({
            allowClear: true,
            placeholder: 'Seleccione una opción'
        });
        
        $('#emprendedorAutocomple').autocomplete({
            minLength: 2,
            source: $('#emprendedorAutocomple').attr('url'),
            search: function(event,ui){
                $("#emprendedorId").val('');
            },
            select: function(event,ui) {
                $("#emprendedorId").val(ui.item.id);
            }
        }); 
        $('#emprendedorAutocomple').blur(function(){
            if( $("#emprendedorId").val()== '')
                $('#emprendedorAutocomple').val('');
        });        
        $('#recomendadorAutocomplete').autocomplete({
            minLength: 2,
            source: $('#recomendadorAutocomplete').attr('url'),
            search: function(event,ui){
                $("#grupo_recomendador").val('');
            },
            select: function(event,ui) {
                $("#grupo_recomendador").val(ui.item.id);
            }
        }); 
        $('#recomendadorAutocomplete').blur(function(){
            if( $("#recomendadorAutocomplete").val()== '')
                $('#grupo_recomendador').val('');
        });        
     });
     
     function editEmprendedor(empId){
        $.facebox({ ajax: '{{path('emprendedor_editar_datos')}}'+'?id='+empId }, 'datosEmprendedor');
     }
     function deleteEmprendedorGrupo(empId){
        if(confirm('Confirma quitar este emprendedor del grupo? ')){
            $.ajax({
                url: '{{path("grupo_remove_emprendedor")}}',
                data: 'empId='+empId+'&grupoId='+'{{entity.id}}',
                //async:false,
                dataType: 'json',
                success: function(data){
                    if(data.msg=='OK')
                        $('#emprendedores').html(data.partial);
                    else{
                        alert('No se puede quitar al emprendedor');
                    }
               }
            });
        }
     }

    function addOptionEmptyToSelect(name){
        // get reference to select element
        var sel = document.getElementById(name);
        // create new option element
        var opt = document.createElement('option');
        // create text node to add to option element (opt)
        opt.appendChild( document.createTextNode('Seleccione una opción') );
        // set value property of opt
        opt.value = -1;
        // add opt to end of select box (sel)
        sel.prepend(opt);
        // $('#'.name).val('-1').change();
        document.getElementById(name).value = -1;
    }

</script>        
{% endblock %}

microcreditos/templates/Grupo/grupoFilter.html.twig
{% extends 'Default/baseFilterEntity.html.twig' %}
{% block filterForm %}      
        <form action="{{ path('grupo') }}" method="post" >
            <fieldset>
                <p>
                    <input type="hidden" id="opFiltro" name="_opFiltro" value="buscar"/>
                    <button class="action align-right clean" onclick="limpiar()" title="Limpiar">Limpiar</button>
                    <button type="submit" id="buscar" class="action align-right search" title="Buscar">Buscar</button>
                    
                    <label><strong>Programa de Fondos:</strong></label>
                    <select name="_programa" id="select_programa" class="smaller-input" url="{{ path('es_programa_individual') }}">
                        <option value="0">---</option>
                    {% for programa in programas %}
                        <option value="{{ programa.id}}" {{ filtro.programa == programa.id ? ' selected="selected"' : '' }} > 
                            {{programa.sigla}} 
                            </option>
                    {% endfor %}            
                    </select>
                    <label><strong>Nombre del Grupo:</strong></label>
                    <input name="_grupo" url="{{ path('grupo_suggest') }}" class="text-input small-input" value="{{filtro.grupo}}" id="grupoAutocomplete" />  
                    <input type="hidden" name="_grupoId" value="{{filtro.grupoId}}" id="grupoId" />     
                </p>
                <p>
                    <label><strong>Fecha Alta:</strong></label>
                    <input name="_desde" class="text-input date-input" value="{{filtro.desde}}" id="fecha_desde_filter" />            
                    <input name="_hasta" class="text-input date-input" value="{{filtro.hasta}}" id="fecha_hasta_filter" />            
                           
                    
                </p>     
                
            </fieldset>    
        </form>
<script type="text/javascript">    
    $(document).ready(function(){
        setTimeout(function(){
            if( isEmpty($('#fecha_desde_filter').val()) && isEmpty($('#fecha_hasta_filter').val())
                && isEmpty($('#grupoId').val()) && $('#select_programa').val()==0 
                && isEmpty($('form :focus').serialize())){
                    $(".content-box-header span.arrow").click();
         }
        },3000);
      });     
    function limpiar(){
        $('#fecha_desde_filter').val('');
        $('#fecha_hasta_filter').val('');
        $('#select_programa').val('');
        $('#grupoAutocomplete').val('');
        $('#grupoId').val('');
        $('#opFiltro').val('limpiar');
        $('#buscar').click();
    }
</script>
{% endblock %}   