microcreditos/src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string $nombre
     *
     * @ORM\Column(name="nombre", type="string", length=100)
     */
    protected $nombre;

    /**
     * @var string $apellido
     *
     * @ORM\Column(name="apellido", type="string", length=100)
     */
    protected $apellido;


    public function getId(){
        return $this->id;
    }

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    public function getTitle(){
        return '" '.$this->getUsername().' - '.$this->getEmail().' "';
    }


    public function setNombre($nombre){
        $this->nombre = $nombre;
    }

    public function getNombre(){
        return $this->nombre;
    }

    public function setApellido($apellido){
        $this->apellido = $apellido;
    }

    public function getApellido(){
        return $this->apellido;
    }

    public function getNombreCompleto(){
        return $this->nombre . ' '. $this->apellido;
    }

    /**
     * Returns whether or not the given user is equivalent to *this* user.
     *
     * The equality comparison should neither be done by referential equality
     * nor by comparing identities (i.e. getId() === getId()).
     *
     * However, you do not need to compare every attribute, but only those that
     * are relevant for assessing whether re-authentication is required.
     *
     * @param UserInterface $user
     *
     * @return Boolean
     */
    public function equals(UserInterface $user)
    {
        if($user->getId() == $this->id){
            return true;
        }
        return false;
    }

    public function getrolesIndex(){
        $string = '';
        $items = $this->getRoles();
        foreach($items as $index => $item){
            if($index == 0){
                $string .=$item;
            }else{
                $string .=', '.$item;
            }
        }
        return $string;
    }

    public function setActivo($status){
        $this->enabled = $status;
    }

    public function getActivo(){
        return  $this->enabled;
    }


}

microcreditos/src/Controller/EmprendedorController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

use App\Entity\Emprendedor;
use App\Form\EmprendedorType;

/**
 * Emprendedor controller.
 *
 */
class EmprendedorController extends Controller
{
    /**
     * Lists all Emprendedor entities.
     *
     */
    public function indexAction()
    {
        $request = $this->container->get('request_stack')->getCurrentRequest();
        $session = $request->getSession();
        $sessionFiltro = $session->get('filtro_emprendedor');
        switch ($request->get('_opFiltro')) {
            case 'limpiar':
                $filtro = array('programa'=>'','grupo'=>'','grupoId'=>'','emprendedor'=>'','emprendedorId'=>'','desde'=>'','hasta'=>'','itemsperpage' => 20);
                break;
            case 'buscar':
                $filtro = array(
                    'programa'      =>$request->get('_programa'),
                    'grupo'         =>$request->get('_grupo'),
                    'grupoId'       =>$request->get('_grupoId'),
                    'emprendedor'   =>$request->get('_emprendedor'),
                    'emprendedorId' =>$request->get('_emprendedorId'),
                    'desde'         =>$request->get('_desde'),
                    'hasta'         =>$request->get('_hasta'),
                    'itemsperpage' => 20);
                break;
            default:
                //desde paginacion, se usa session
                $filtro = array(
                    'programa'      =>$sessionFiltro['programa'],
                    'grupo'         =>$sessionFiltro['grupo'],
                    'grupoId'       =>$sessionFiltro['grupoId'],
                    'emprendedor'   =>$sessionFiltro['emprendedor'],
                    'emprendedorId' =>$sessionFiltro['emprendedorId'],
                    'desde'         =>$sessionFiltro['desde'],
                    'hasta'         =>$sessionFiltro['hasta'],
                    'itemsperpage' => 20);
                break;
        }
                   
        $session->set('filtro_emprendedor',$filtro);
        $em = $this->getDoctrine()->getManager();

        $paginator = $this->get('knp_paginator');
        $query = null;
        $varItems = ($filtro['itemsperpage']==0) ? 1000 : $filtro['itemsperpage'];
        $query =  $em->getRepository('App:Emprendedor')
            ->findByMyFiltroDQL($session->get('filtro_emprendedor'));

        $entities = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        $programas = $em->getRepository('App:Programa')->findByActivosDQL();
        $vars = array(  
            'entityName'   => 'emprendedor',
            'filtro'       => $session->get('filtro_emprendedor'),
            'entities'     => $entities,
            'paginator'    => $paginator,
            'programas'    => $programas);
       
        return $this->render('Emprendedor/emprendedorIndex.html.twig', $vars );
    }    

    /**
     * Finds and displays a Emprendedor entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('App:Emprendedor')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('No existe el Emprendedor que está buscando.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm( EmprendedorType::class, $entity);


        return $this->render('Emprendedor/show.html.twig', array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),

        ));
    }

    /**
     * Displays a form to create a new Emprendedor entity.
     *
     */
    public function newAction()
    {
        $entity = new Emprendedor();
        $em = $this->getDoctrine()->getManager();
        $ultimo = $em->getRepository('App:Parametro')->getUltimoNroDQL('Emprendedor');
        $nro = $ultimo->getNumerico()+1;
        $codigo = $ultimo->getDescripcion().str_pad($nro,4,"0",STR_PAD_LEFT);
        $entity->setCodigo($codigo);
        $form   = $this->createForm( EmprendedorType::class, $entity);
        return $this->render('Emprendedor/emprendedorEdit.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
    }

    /**
     * Creates a new Emprendedor entity.
     *
     */
    public function createAction()
    {
        $entity  = new Emprendedor();
        $request = $this->container->get('request_stack')->getCurrentRequest();
        $form    = $this->createForm( EmprendedorType::class, $entity);
        $em = $this->getDoctrine()->getManager();
        if ($request->isMethod('POST')) {
            $requestData = $request->get($form->getName());
            $form->submit($requestData);

            if( $em->getRepository('App:Emprendedor')->checkUniqueDNI($requestData['dni']) == 0){

                if ($form->isValid()) {

                    $ultimo = $em->getRepository('App:Parametro')->getUltimoNroDQL('Emprendedor');
                    $nro = $ultimo->getNumerico() + 1;
                    $codigo = $ultimo->getDescripcion() . str_pad($nro, 4, "0", STR_PAD_LEFT);
                    $ultimo->setNumerico($nro);
                    $entity->setCodigo($codigo);
                    $em->persist($entity);
                    $em->persist($ultimo);
                    $em->flush();
                    $session = $request->getSession();
                    $session->getFlashBag()->set('success', 'El Emprendedor se ha creado con éxito');
                    return $this->redirect($this->generateUrl('emprendedor_edit', array('id' => $entity->getId())));
                }
            }else{
                $session = $request->getSession();
                $session->getFlashBag()->set('error', 'Ya existe un Emprendedor con ese DNI');
            }
        }

        return $this->render('Emprendedor/emprendedorEdit.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
    }

    /**
     * Displays a form to edit an existing Emprendedor entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('App:Emprendedor')->find($id);


        if (!$entity) {
            throw $this->createNotFoundException('No existe el Emprendedor que está buscando.');
        }

        $request = $this->container->get('request_stack')->getCurrentRequest();
        //controla si tiene algun credito dado
        $creditos = $entity->getCreditos();
        //if(count($creditos) > 0){
        //    $session = $request->getSession();
        //    $session->getFlashBag()->set('error','No se pudo Editar el Emprendedor por que tiene Creditos entregados');
        //    return $this->redirect($this->generateUrl('emprendedor_show', array('id' => $id)));
        //}

//        $grupo = $entity->getGrupo();
//        if(count($grupo->getCreditos()) > 0){
//            $session = $request->getSession();
//            $session->getFlashBag()->set('error','No se pudo Editar el Emprendedor por que tiene Creditos entregado en el grupo');
//            return $this->redirect($this->generateUrl('emprendedor_show', array('id' => $id)));
//        }

        $editForm = $this->createForm( EmprendedorType::class, $entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('Emprendedor/emprendedorEdit.html.twig', array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }


    /**
     * Edits an existing Emprendedor entity.
     *
     */
    public function updateAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('App:Emprendedor')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('No existe el Emprendedor que está buscando.');
        }

        $editForm   = $this->createForm( EmprendedorType::class, $entity);
        $deleteForm = $this->createDeleteForm($id);

        $request = $this->container->get('request_stack')->getCurrentRequest();

        if ($request->isMethod('POST')) {
            $requestData = $request->get($editForm->getName());
            $editForm->submit($requestData);
            //var_dump($em->getRepository('App:Emprendedor')->checkUniqueDNI($requestData['dni'],$id));exit;
            if( $em->getRepository('App:Emprendedor')->checkUniqueDNI($requestData['dni'],$id) == 0) {
                if ($editForm->isValid()) {
                    $em->persist($entity);
                    $em->flush();
                    $session = $request->getSession();
                    $session->getFlashBag()->set('success', 'Los cambios se han guardado con éxito');
                    return $this->redirect($this->generateUrl('emprendedor_edit', array('id' => $id)));
                }
            }else{
                $session = $request->getSession();
                $session->getFlashBag()->set('error', 'Ya existe un Emprendedor con ese DNI');
            }

        }

        return $this->render('Emprendedor/emprendedorEdit.html.twig', array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    public function updateInfoAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('App:Emprendedor')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('No existe el Emprendedor que está buscando.');

microcreditos/templates/Emprendedor/_partial_datos_basicos.html.twig
<style>
.small-input{ width: 30% !important }
.medium-input{ width: 60% !important }
</style>
<div id="main-content" class="pagocuota">
    <div style="margin-top:25px" class="content-box">
        <div class="content-box-header">
            <h3>Datos Emprendedor {{emprendedor.codigo}}</h3>
        </div>
        <div class="content-box-content">
            <form> 
                <fieldset >
                    <p>
                        {{ form_label(form.apellido) }}
                        {{ form_widget(form.apellido, { 'attr': { 'class' : 'text-input small-input' } }) }}
                        {{ form_label(form.nombres) }}
                        {{ form_widget(form.nombres, { 'attr': { 'class' : 'text-input small-input' } }) }}
                    </p>
                    <p>
                        {{ form_label(form.dni) }}
                        {{ form_widget(form.dni, { 'attr': { 'class' : 'text-input smaller-input' } }) }}
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        {{ form_label(form.cbu) }}
                        {{ form_widget(form.cbu, { 'attr': { 'class' : 'text-input smaller-input' } }) }}
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        {{ form_label(form.sexo) }}
                        {{ form_widget(form.sexo) }}
                     </p>
                    <p>
                        {{ form_label(form.direccion) }}
                        {{ form_widget(form.direccion, { 'attr': { 'class' : 'text-input medium-input' } }) }}
                     </p>
                     <p>
                        {{ form_label(form.ubicacion) }}
                        {{ form_widget(form.ubicacion, { 'attr': { 'class' : 'text-input small-input' } }) }}

                        {{ form_label(form.telefono) }}
                        {{ form_widget(form.telefono, { 'attr': { 'class' : 'text-input small-input' } }) }}
                     </p>
                     <p>
                        {{ form_label(form.DatosAdicionales.actividad) }}
                        {{ form_widget(form.DatosAdicionales.actividad, { 'attr': { 'class' : 'text-input medium-input' } }) }}
                     </p>
                </fieldset> 
                <div style="display:none" > 
                     <input value="{{emprendedor.id}}" name="id" class="id" id="id" type="hidden"/>
                    {{ form_rest(form) }}
                       
                </div>
            </form>
        </div>
    </div>        
        <div class="align-center" style="margin-bottom: 10px ">
        <button type="button" id="registrar" class="button" style="margin-left: 15px">Guardar los cambios</button>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#registrar').click(function(){
            if( $('#emprendedor_dni').val() == ''){
                alert('Debe ingresar el DNI');
                return false;
            }else{
                $('#emprendedor_dni').val(
                    parseInt($('#emprendedor_dni').val())
                )
            }
            if( $('#emprendedor_apellido').val() == ''){
                alert('Debe ingresar Apellido');
                return false;
            }

            if( $('#emprendedor_nombres').val() == ''){
                alert('Debe ingresar Nombre');
                return false;
            }

            if( $('#emprendedor_nombres').val() == ''){
                alert('Debe ingresar Nombre');
                return false;
            }

            if( $('#emprendedor_direccion').val() == ''){
                alert('Debe ingresar la Dirección');
                return false;
            }

            if( $('#emprendedor_telefono').val() == ''){
                alert('Debe ingresar la Telefono');
                return false;
            }


            $.ajax({
                url: '{{path("emprendedor_guardar_datos")}}',
                data: $('form').serialize(),
                async:false,
                dataType: 'json',
                success: function(data){
                    if(data!='error'){
                        emp = $('#emprendedor_'+'{{emprendedor.id}}');
                        dni = $('#lbldni_'+'{{emprendedor.id}}');
                        if( emp.val()==undefined ){
                            $('#emprendedorAutocomplete').val(data.nombre);
                            $('#lbldni').html(data.dni);
                        }else{
                            $('#lblnom_'+'{{emprendedor.id}}').html(data.codigo+' - '+data.nombre);
                            dni.html(data.dni);
                        }
                    }
                    $(document).trigger('close.facebox');
               }
           });


        });
    });
</script>    

microcreditos/templates/Emprendedor/emprendedorEdit.html.twig
{% extends "Default/baseEditEntity.html.twig" %}
{% block pageTitle %} <h2>Emprendedores </h2>{% endblock %}

{% block pathback %}   {{ path('emprendedor') }}           {% endblock %}
{% block pathCreate %} {{ path('emprendedor_create') }}    {% endblock %}
{% block pathDelete %} {{path('emprendedor_delete', { 'id': entity.id })}} {% endblock %}
{% block pathUpdate %} {{path('emprendedor_update', { 'id': entity.id })}} {% endblock %}

{% block formContent %}
<div class="clear" ></div>
<div class="content-box">
    <div class="content-box-header">
        <ul class="content-box-tabs">
            <li><a id="a_tabGroup1" href="#tabGroup1" class="default-tab"><strong>Datos Personales</strong></a></li> 
            <li><a id="a_tabGroup2" href="#tabGroup2" >Datos del Negocio</a></li> 
            <li><a id="a_tabGroup4" href="#tabGroup3" >Datos del Cónyuge</a></li>
            <li><a id="a_tabGroup5" href="#tabGroup4" >Grupos</a></li>
        </ul>
    </div>
    <div class="content-box-content">    
        <div class="tab-content default-tab" id="tabGroup1">   
            {% include "Emprendedor/emprendedorEdit_datosPersonales.html.twig" %}
        </div>
        <div class="tab-content" id="tabGroup2"> 
            {% include "Emprendedor/emprendedorEdit_datosNegocio.html.twig" %}
        </div>            
        <div class="tab-content" id="tabGroup3"> 
            {% include "Emprendedor/emprendedorEdit_datosConyuge.html.twig" %}
        </div>
        <div class="tab-content" id="tabGroup4">
            {% include "Emprendedor/emprendedorEdit_datosGrupos.html.twig" %}
        </div>
    </div>  
        
        
</div>
{{ form_rest(form) }}

<script type="text/javascript"> 
 $(document).ready(function(){

    initForms();

    $('#emprendedor_programa').change(function(){
        $('#loading').fadeIn();
        console.log($(this).val());
        if($(this).val() != "") {
            $.ajax({
                url: $(this).attr('url'),
                data: 'id=' + $(this).val(),
                async: false,
                dataType: 'json',
                success: function (data) {
                    if (data) {
                        $('#emprendedor_grupo').attr('disabled', 'true');
                        // $('#grupoAutocomplete').attr('disabled','true');
                        $('#emprendedor_DatosAdicionales_actividad').removeAttr('required');
                    }
                    else {
                        $('#emprendedor_grupo').removeAttr("disabled");
                        // $('#grupoAutocomplete').removeAttr("disabled");
                        $('#emprendedor_DatosAdicionales_actividad').attr('required', 'required');
                    }
                    $("#emprendedor_grupo").val('');
                    // $('#grupoAutocomplete').val('');
                    $('#loading').fadeOut();
                }
            }).fail(function () {
                $('#loading').fadeOut();
                alert("No es posible realizar esta operación en este momento.");
            });
        }else{
            document.getElementById('emprendedor_grupo').value = -1;
            $('#emprendedor_grupo').trigger('change');
            $('#emprendedor_grupo').attr('disabled', 'true');
            $('#loading').fadeOut();

        }
    });

    // verificar que tenga grupo, sino deshabilitar
    if($('#emprendedor_programa').val()==5)
        $('#grupoAutocomplete').attr('disabled','true');
    $('#submitForm').click( function(){
        var tab = $('input:required:invalid').closest(".tab-content").attr('id');
        $('#a_'+tab).click();
    });
    
    // $('#emprendedorAutocomplete').autocomplete({
    //     minLength: 2,
    //     source: $('#emprendedorAutocomplete').attr('url'),
    //     search: function(event,ui){
    //         $("#emprendedor_recomendador").val('');
    //     },
    //     select: function(event,ui) {
    //         $("#emprendedor_recomendador").val(ui.item.id);
    //     }
    // });
    // $('#emprendedorAutocomplete').blur(function(){
    //     if( $("#emprendedorAutocomplete").val()== ''){
    //         $('#emprendedor_recomendador').val(''); }
    // });
    
});


 function initForms() {
     addOptionEmptyToSelect('emprendedor_grupo');

     // $('#emprendedor_grupo').select2({
     //     placeholder: 'Seleccione una opción'
     // });

     $('#emprendedor_recomendador').select2({
         placeholder: 'Seleccione una opción'
     });

     $('#emprendedor_grupo').attr('disabled','true');

     myDate = new Date();
     if(!isEmpty($('#emprendedor_fecha_nacimiento').val())){
         myDate = $('#emprendedor_fecha_nacimiento').val();
     }
     $('#emprendedor_fecha_nacimiento').datepicker(
         {
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });
     $('#date').datepicker('setDate', myDate);

 }
 function addOptionEmptyToSelect(name){
     // get reference to select element
     var sel = document.getElementById(name);
     // create new option element
     var opt = document.createElement('option');
     // create text node to add to option element (opt)
     opt.appendChild( document.createTextNode('Seleccione una opción') );
     // set value property of opt
     opt.value = -1;
     // add opt to end of select box (sel)
     sel.prepend(opt);
     // $('#'.name).val('-1').change();
     document.getElementById(name).value = -1;
 }

</script>    
{% endblock %}

microcreditos/templates/Emprendedor/emprendedorEdit_datosConyuge.html.twig
<fieldset >
    <p>
        {{ form_label(form.DatosAdicionales.nombres_conyuge) }}
        {{ form_widget(form.DatosAdicionales.nombres_conyuge, { 'attr': { 'class' : 'text-input small-input' } }) }}

        {{ form_label(form.DatosAdicionales.apellido_conyuge) }}
        {{ form_widget(form.DatosAdicionales.apellido_conyuge, { 'attr': { 'class' : 'text-input small-input' } }) }}

        {{ form_label(form.DatosAdicionales.dni_conyuge) }}
        {{ form_widget(form.DatosAdicionales.dni_conyuge, { 'attr': { 'class' : 'text-input smaller-input' } }) }}
    </p>
    <p>
        {{ form_label(form.DatosAdicionales.lugar_nacimiento_conyuge) }}
        {{ form_widget(form.DatosAdicionales.lugar_nacimiento_conyuge, { 'attr': { 'class' : 'text-input smaller-input' } }) }}

        {{ form_label(form.DatosAdicionales.fecha_nacimiento_conyuge) }}
        {{ form_widget(form.DatosAdicionales.fecha_nacimiento_conyuge, { 'attr': { 'class' : 'text-input date-input datepicker' } }) }}
    </p>
    <p>
        {{ form_label(form.DatosAdicionales.nivel_educativo_conyuge) }}
        {{ form_widget(form.DatosAdicionales.nivel_educativo_conyuge, { 'attr': { 'class' : 'text-input smaller-input' } }) }}

        {{ form_label(form.DatosAdicionales.actividad_conyuge) }}
        {{ form_widget(form.DatosAdicionales.actividad_conyuge, { 'attr': {'class' : 'text-input medium-input' } }) }}
     </p>
</fieldset>

microcreditos/templates/Emprendedor/emprendedorEdit_datosPersonales.html.twig
<fieldset >
    <p>
        {{ form_label(form.codigo) }}
        {{ form_widget(form.codigo, { 'attr': {'class' : 'text-input smaller-input', 'readonly':'readonly' } }) }}

        {{ form_label(form.programa) }}
        {{ form_widget(form.programa, { 'attr': { 'class' : 'text-input smaller-input', 'url' : path('es_programa_individual') } }) }}

        {#{{ form_label(form.grupo) }}#}
        {#{{ form_widget(form.grupo) }}#}
            {#<input name="_grupo" url="{{ path('grupo_suggest') }}" required="required" class="text-input small-input" value="{{entity.grupo}}" id="grupoAutocomplete" />  #}
    </p>
    <p>
        {{ form_label(form.nombres) }}
        {{ form_widget(form.nombres, { 'attr': { 'class' : 'text-input small-input' } }) }}

        {{ form_label(form.apellido) }}
        {{ form_widget(form.apellido, { 'attr': { 'class' : 'text-input small-input' } }) }}

        {{ form_label(form.dni) }}
        {{ form_widget(form.dni, { 'attr': { 'class' : 'text-input mini-input' } }) }}
        {{ form_label(form.cuit) }}
        {{ form_widget(form.cuit, { 'attr': { 'class' : 'text-input mini-input' } }) }}
     
        {{ form_label(form.email) }}
          {{ form_widget(form.email, { 'attr': { 'class' : 'text-input mini-input' } }) }}
        {{ form_label(form.cbu) }}
         {{ form_widget(form.cbu, { 'attr': { 'class' : 'text-input mini-input' } }) }}
    </p>
    <p>
        <div>
        {{ form_label(form.sobrenombre) }}
        {{ form_widget(form.sobrenombre, { 'attr': { 'class' : 'text-input smaller-input' } }) }}
            
        {{ form_label(form.estado_civil) }}
        {{ form_widget(form.estado_civil, { 'attr': { 'class' : 'text-input smaller-input' } }) }}


        {{ form_label(form.sexo) }}
        {{ form_widget(form.sexo, { 'attr': { 'class' : 'text-input smaller-input' } }) }}
        </div>
     </p>
     <p>
        {{ form_label(form.lugar_nacimiento) }}
        {{ form_widget(form.lugar_nacimiento, { 'attr': { 'class' : 'text-input smaller-input' } }) }}

        {{ form_label(form.fecha_nacimiento) }}
        {{ form_widget(form.fecha_nacimiento, { 'attr': { 'class' : 'text-input date-input datepicker' } }) }}

        {{ form_label(form.nivel_educativo) }}
        {{ form_widget(form.nivel_educativo, { 'attr': { 'class' : 'text-input smaller-input' } }) }}
     </p>
     <p>
        {{ form_label(form.direccion) }}
        {{ form_widget(form.direccion, { 'attr': { 'class' : 'text-input medium-input' } }) }}
     </p>
     <p>
        {{ form_label(form.ubicacion) }}
        {{ form_widget(form.ubicacion, { 'attr': { 'class' : 'text-input small-input' } }) }}

        {{ form_label(form.telefono) }}
        {{ form_widget(form.telefono, { 'attr': { 'class' : 'text-input small-input' } }) }}
     </p>
     <p>
        {{ form_label(form.tipo_vivienda) }}
        {{ form_widget(form.tipo_vivienda, { 'attr': { 'class' : 'text-input mini-input' } }) }}

        {{ form_label(form.tiempo_residencia) }}
        {{ form_widget(form.tiempo_residencia, { 'attr': { 'class' : 'text-input mini-input' } }) }}
     </p>
     <p>{{ form_label(form.recomendador) }}
        {{ form_widget(form.recomendador) }}
        {#<input name="_emprendedor" url="{{ path('emprendedor_suggest') }}" class="text-input small-input" value="{{entity.recomendador}}" id="emprendedorAutocomplete" />  #}
     </p>
     <p>
         {{ form_label(form.aclaraciones)}}
        {{ form_widget(form.aclaraciones) }}
     </p>
     <p style="text-align: center">
        {{ form_label(form.activo) }}
        {{ form_widget(form.activo) }}
     </p>
</fieldset>

microcreditos/templates/Emprendedor/opList.html.twig
<div class="content-popup"> 
    <h3>Impresión y Exportación de Datos</h3>
    <div style="margin: 15px">
        <h4>Opciones de Reporte</h4>
        <input type="radio" checked="checked" value="R" name="opReporte"><label>Reducido</label>
        <input type="radio" value="D" name="opReporte"><label>Detallado</label>
    </div>

    <div style="margin: 15px">
        <h4>Opciones de Salida</h4>
        <button id="listXls" style="margin: 15px" >XLS</button>
        <button id="listPdf" style="margin: 15px" >PDF</button>
    </div>
</div>
<script type="text/javascript">    
    $(document).ready(function(){
        $('#listPdf').click(function(){  sendList('PDF');  });
        $('#listXls').click(function(){  sendList('XLS');  });
      });     
      function sendList(format){
            var op = $('input[name="opReporte"]:checked').val();
            var url = '{{path('emprendedor_get_data')}}';
            window.location.href=url+'?format='+format+'&option='+op;
      }
</script>